### ISSUE TITLE
Question about your paper

### ISSUE THREAD

**Issue by luciaL** [balakg/voxelmorph#5]
I've read your work on CVPR2018 and  I have to say this is  really an efficient work. I have a question about Tabel 1 in the paper at the Result part. There  is a number in  Parentheses behind the  result of every method and every index. What does that mean? I don't find its explaination.

**Comment by balakg** [comment]
That's the standard deviation for each result.

**Comment by luciaL** [comment]
oh, thank you so much for your reply.
