### ISSUE TITLE
Atlas Dataset for Stroke

### ISSUE THREAD

**Issue by Matt-arch** [balakg/voxelmorph#6]
hello there, I was working on an svm classifier which classifies the type of stroke for this project i am using the atlas dataset, the dataset have more than 200 stroke mri in the format of .nii, how can i load all of this .nii files in python using nibabel library

**Comment by adalca** [comment]
please refer to the nibabel github: https://github.com/nipy/nibabel/issues
`nibabel.load` is probably what you're looking for.

**Comment by Matt-arch** [comment]
i can't find any solution, what confuses me is that each MRI image is in different sub folders, each sub i can't figure out how to load it

**Comment by Matt-arch** [comment]
> please refer to the nibabel github: https://github.com/nipy/nibabel/issues
> `nibabel.load` is probably what you're looking for.

what i can't figure out is that how can i load multiple .nii files from different sub folders, i am using the atlas dataset for stroke

**Comment by adalca** [comment]
try a for loop? somethign like (i didn't test this)

```
volumes = []
for subfolder in os.listdir(main_folder):
    filename = os.path.join(main_folder, sub_folder, 'filename.nii')
    volumes.append(nib.load(filename).get_fdata())
```

**Comment by Matt-arch** [comment]
> try a for loop? somethign like (i didn't test this)
> 
> ```
> volumes = []
> for subfolder in os.listdir(main_folder):
>     filename = os.path.join(main_folder, sub_folder, 'filename.nii')
>     volumes.append(nib.load(filename).get_fdata())
> ```
i tried in this way i load all the .nii files in the buffer, then when i try to get the mri images from the buffer  i got this 'FileNotFoundError: No such file or no access: '031945_LesionSmooth_stx.nii.gz' 
i tried in your ways to the problem is the same, please help me out here, my code is as follows
import nibabel as nib
import os
buffer = []
for (root, sub, files) in os.walk("/home/matt/ATLAS_Dataset/ATLAS_R1.1/", topdown=True):
    for file in files:
        if file.endswith('_LesionSmooth_stx.nii.gz'):
            buffer.append(file)
        print(buffer)
length = len(buffer)
print(length)
mri_image = []
for mri in buffer:
    mri_image.append(nib.load(mri).get_fdata())
`

**Comment by adalca** [comment]
@Matt-arch 

The way you wrote it, `files` will only contain the relative file names, not the full path, so doing `nib.load(mri)` will fail since `mri` does not contain the full (absolute) path. You need to get the full path.

Please move this discussion to https://github.com/nipy/nibabel/issues , the nibabel discussion board for further support.

**Comment by Matt-arch** [comment]
thank you for your comment it help me a lot, i am a beginner to ML, how can i convert the data to tensor should i use panda or pytorch tensorflow doesn't work in my laptop, i try by downgrading it too, but still doesn't work, am using muticlass svm for the classification here is my code below
import nibabel as nib
import os
for (root, sub, files) in os.walk("~/ATLAS_Dataset/ATLAS_R1.1", topdown=True):
    for file in files:
        if file.endswith('_LesionSmooth_stx.nii.gz'):
            mri_file = os.path.join(root, file)
            print(mri_file)
            file, files, sub, root = None
            mri_img = nib.load(mri_file).get_fdata()
            print(mri_img.header())
            mri_file, mri_img = None
