### ISSUE TITLE
An Unsupervised Learning Model for Deformable Medical Image Registration

### ISSUE THREAD

**Issue by Paluck1Arora2** [balakg/voxelmorph#7]
Respected,
Kindly provide the dataset of your code "https://github.com/balakg/voxelmorph/" which mentioned in train.py file
base_data_dir = '/insert/your/path/here'
train_vol_names = glob.glob(base_data_dir + 'train/vols/*.npz')
random.shuffle(train_vol_names)
**We demonstrate our method on the task of brain MRI registration. We use a large-scale, multi-site, multi-study
dataset of 7829 T1weighted brain MRI scans from eight publicly available datasets: ADNI [33], OASIS [29], ABIDE [31], ADHD200 [32], MCIC [19], PPMI [30], HABS [12], and Harvard GSP [20].** These lines mentioned in the dataset part of the paper. Can you please help me out. Please provide the dataset which was used in the code.

Thanks.

**Comment by adalca** [comment]
@Paluck1Arora2 because of the requirements of all those datasets, we cannot share the original datasets. However, we prepared some data that you can use at https://github.com/adalca/medical-datasets/blob/master/neurite-oasis.md.

Please note that the voxelmorph github as moved to http://voxelmorph.net/

**Comment by Paluck1Arora2** [comment]
Hi sir,
Thank you so much for the reply.
Sir, can you please help me how it works with this dataset. I wasn't able
to download this dataset. It was very helpful for me.

**Comment by adalca** [comment]
What error did you get when downloading the dataset? The links should work. E.g. for 2D: https://surfer.nmr.mgh.harvard.edu/ftp/data/neurite/data/neurite-oasis.2d.v1.0.tar

**Comment by Paluck1Arora2** [comment]
Hlo sir,
I'm not able to download 3D images dataset. Can you please help me out.
Also, I used different dataset at the place of base_data_dir.
base_data_dir = '/insert/your/path/here'
train_vol_names = glob.glob(base_data_dir + 'train/vols/*.npz')

i used "
https://www.kaggle.com/code/yeonghyeon/convert-dicom-to-numpy-array-super-simple/data"
this dataset.
i faced this error
[image: image.png]

Kindly help me to resolve this issue.

**Comment by adalca** [comment]
>> I'm not able to download 3D images dataset. Can you please help me out.

Can you please tell me what the problem/error is?

>> i faced this error [image: image.png]

This is an interesting dataset, but not one we are familiar with. I also don't see the image.

**Comment by Paluck1Arora2** [comment]
This is the link of file
https://colab.research.google.com/drive/1HY3Sida46lRbbEQlZMSf0GsAn5FMBJvG?usp=sharing
This is the link to the dataset.
https://drive.google.com/drive/folders/1dnjYoVolFc2NYYiKpnxsPXXQdOpeOXMo?usp=sharing
Following this dataset
https://www.kaggle.com/code/yeonghyeon/convert-dicom-to-numpy-array-super-simple/data
I have changed the path --train.py
Can you please resolve this issue.

**Comment by adalca** [comment]
Sorry but you are not answering the question about the dataset.

What error did you get when downloading the dataset? The links should work. E.g. for 2D: https://surfer.nmr.mgh.harvard.edu/ftp/data/neurite/data/neurite-oasis.2d.v1.0.tar

As mentioned, this current repository is quite old, please use the code at [voxelmorph.net](https://github.com/voxelmorph/voxelmorph)

We also have an extensive tutorial on how to use voxelmorph at http://tutorial.voxelmorph.net/

**Comment by Paluck1Arora2** [comment]
Hi,
I studied http://tutorial.voxelmorph.net/ this tutorial. In which one
medical dataset is discussed which also has one static image.
I checked this code https://github.com/voxelmorph/voxelmorph but facing the
problem in the same. This is not executing.

**Comment by Paluck1Arora2** [comment]
https://colab.research.google.com/drive/1FG78lk9P89mvtU62U_PRkhiKXwSGXDG4?usp=sharing
 I have checked https://github.com/voxelmorph/voxelmorph this code but
facing issue. Can you please fix thi sissue

**Comment by Paluck1Arora2** [comment]
Hi,
Can you please resolve this issue.

**Comment by Paluck1Arora2** [comment]
Hi,
[image: image.png]
[image: image.png]
I'm getting these types of errors. Can you please resolve this issue

**Comment by adalca** [comment]
I cannot see these images, it simply says [image: image.png]. When you send images, please try to make sure they show up on the github page.

I quickly coded up a colab that shows how to train on the OASIS data that we preprocessed and provide freely: https://colab.research.google.com/drive/1ZefmWXBupRNsnIbBbGquhVDsk-7R7L1S?usp=sharing

**Comment by Paluck1Arora2** [comment]
Hi, please check this colab notebook "
https://colab.research.google.com/drive/1FG78lk9P89mvtU62U_PRkhiKXwSGXDG4?usp=sharing
"
I'm facing these issues.Can you please resolve it.
Thank you so much for the reply.

**Comment by adalca** [comment]
Sorry, we don't have the bandwidth to closely debug user's scripts. 
I provided a colab above that works from scratch -- downloads recent voxelmorph from the git, downloads OASIS, and starts training with `train.py`. I recommend you remove all your files from scratch and try again using this tutorial. It shold work and give you a starting point.

**Comment by Paluck1Arora2** [comment]
Thank you so much sir.
I got error in your file.

**Comment by Paluck1Arora2** [comment]
Hlo sir,
Can you please tell me how to compute the average dice score in a voxel
morph tutorial in 2d images.
https://colab.research.google.com/drive/1WiqyF7dCdnNBIANEY80Pxw_mVz4fyV-S?usp=sharing#scrollTo=1axrla6VPXPf

**Comment by Paluck1Arora2** [comment]
Hi sir,
Can you please inform me how to compute gpu time and different values of
lambda in 3d voxelmorph. Please resolve these issues .
https://www.kaggle.com/code/kmader/voxelmorph-demo/notebook

**Comment by Paluck1Arora2** [comment]
Sir, you have written paper and many codes in this area. Kindly help me to
resolve the issues!

**Comment by adalca** [comment]
As mentioned, this is not the right github repository. Please refer to [voxelmorph](http://voxelmorph.mit.edu/)
